#!/usr/bin/env python3

import subprocess
import struct
import sys
import os


def compile_shader(glsl_path, stage):
    spv_path = glsl_path.replace(".glsl", ".spv")
    result = subprocess.run(
        ["glslangValidator", "-V", "-S", stage, "-o", spv_path, glsl_path],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"err compiling {glsl_path}:", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    with open(spv_path, "rb") as f:
        data = f.read()

    assert len(data) % 4 == 0
    words = struct.unpack(f"<{len(data) // 4}I", data)
    return words


def main():
    shader_dir = "shaders"
    out_path = "src/rvShShdr.hpp"

    vert_words = compile_shader(os.path.join(shader_dir, "overlay.vert.glsl"), "vert")
    frag_words = compile_shader(os.path.join(shader_dir, "overlay.frag.glsl"), "frag")

    with open(out_path, "w") as f:
        f.write("// auto generated by compile_shaders.py\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstddef>\n\n")

        f.write("namespace RV {\n\n")

        f.write("    static const uint32_t s_aOverlayVertSpv[] = {\n")
        for i in range(0, len(vert_words), 8):
            chunk = vert_words[i : i + 8]
            f.write("        " + ", ".join(f"0x{w:08x}" for w in chunk) + ",\n")
        f.write("    };\n")
        f.write(
            "    static const size_t s_iOverlayVertSpvSize = sizeof(s_aOverlayVertSpv);\n\n"
        )

        f.write("    static const uint32_t s_aOverlayFragSpv[] = {\n")
        for i in range(0, len(frag_words), 8):
            chunk = frag_words[i : i + 8]
            f.write("        " + ", ".join(f"0x{w:08x}" for w in chunk) + ",\n")
        f.write("    };\n")
        f.write(
            "    static const size_t s_iOverlayFragSpvSize = sizeof(s_aOverlayFragSpv);\n\n"
        )

        f.write("}\n")

    print(f"gg {out_path}")


if __name__ == "__main__":
    main()
